/*
 * A179962 and the general fixed-k family -- certified for 2<=k<=7.
 *
 * IMPORTANT STATUS
 * ----------------
 * There are three distinct proof statuses.
 *
 *   (1) For every fixed k, a finite insertion-state representation proves
 *       that A_k(n) satisfies some constant-coefficient linear recurrence.
 *   (2) For each k=2,...,7, an exact finite-window certificate proves that
 *       the recurrence C_k used below holds from its stated sharp boundary.
 *       Thus every value generated by this program for k<=7 is proved equal
 *       to the combinatorial definition, not merely fitted or extrapolated.
 *   (3) For k=8, C_8 has only been checked on a finite prefix: the certificate
 *       requires 13628 consecutive residual zeros (the current script uses
 *       the safer 13629), and that computation has not been completed.
 *       A uniform proof identifying C_k for arbitrary k is also open.
 *
 * The complete finite-state invariant, transition multiplicities, certification
 * lemma, and execution records are in files/proved_results.md.  The recurrence
 * implementation itself is unchanged by this proof-status update.
 *
 * The older determinant/sector development recorded in this comment proves:
 *   A1--A3: an exact finite gadget/sector decomposition;
 *   B0--B2: a division-free all-minors Matrix-Tree dictionary in a
 *           truncated polynomial ring;
 *   Proposition C0: an obstruction showing that the earlier reflection
 *                   folding/Jordan explanation cannot be correct as written.
 *
 * That development still does not prove a uniform spectral law: its proposed
 * stationary transfer, diagonal r*(k-r), odd-k Jordan chain, and exact
 * transient length max(0,k-3) remain conjectural in general.  They are not
 * needed for the fixed-k certificates for k=2,...,7.
 *
 * NOTATION
 * --------
 * Fix k>=2 and n>=k-1.  Put N=2*n+k, V=[N], and let G=G_{n,k} have
 *
 *                    u~v  iff  |u-v|>n.
 *
 * A_k(n) is the number of oriented Hamilton paths of G.  Split
 *
 *   L={1,...,n},  M={n+1,...,n+k},  R={n+k+1,...,2*n+k},
 *
 * write L_i=i, M_s=n+s, R_j=n+k+j, and put
 *
 *   Gamma_L={1,...,k-1},
 *   Gamma_R={2*n+2,...,2*n+k},  Gamma=Gamma_L union Gamma_R,
 *   S=G-M.
 *
 * Direct calculation gives
 *
 *   L_i R_j iff i<k+j,
 *   N(M_s)={1,...,s-1} union {2*n+s+1,...,2*n+k} subset Gamma.
 *
 * Thus L,R,M are independent sets (for M use n>=k-1), S is a balanced
 * staircase/Ferrers graph, every Gamma_L vertex is adjacent in S to every
 * R vertex, and every Gamma_R vertex is adjacent in S to every L vertex.
 * In particular Sym(Gamma_L) x Sym(Gamma_R) acts by automorphisms of S.
 *
 * LEMMA A1 (GADGET DECOMPOSITION) -- PROVED
 * ------------------------------------------------
 * A gadget g assigns to each s a set
 *
 *       g(s) subset N(M_s),  |g(s)| in {1,2},
 *
 * and denotes the edge set {M_s gamma : gamma in g(s)}.  Deleting M from
 * an unoriented Hamilton path P gives a spanning linear forest F_P of S,
 * while the P-edges incident with M give a gadget g_P.  Conversely F and g
 * reconstruct P exactly when F union g is a Hamilton path.  Hence
 *
 *   {unoriented HPs of G}
 *       <-> {(g,F): F is a spanning linear forest of S and F union g is HP},
 *
 * and, with N_g(n)=#{F:F union g is a Hamilton path},
 *
 *                  A_k(n)=2*Sum_g N_g(n).                    (A1)
 *
 * The factor two orients the nontrivial path.  Each M_s has k-1 possible
 * neighbors, so the number of gadgets is
 *
 *       Product_s ((k-1)+binomial(k-1,2)) <= (k^2/2)^k,
 *
 * a constant depending only on k.
 *
 * Proof.  M is independent and N(M_s) is contained in Gamma.  Every M_s
 * has path-degree one or two.  Removing M therefore leaves disjoint paths
 * spanning L union R; all their edges lie in S.  Taking the union with the
 * recorded M-edges is the inverse operation.  This proves the bijection and
 * (A1).  The displayed neighbor count proves finiteness.  QED.
 *
 * LEMMA A2 (TRACE COLLAPSE AND THE DEFINITION OF A SECTOR) -- PROVED
 * ------------------------------------------------------------------
 * A gadget containing a cycle or a vertex of degree at least three has
 * N_g=0 and may be discarded.  Every remaining gadget component is a chain
 * alternating between Gamma and M.  Give each chain endpoint type
 *
 *   L: an endpoint in Gamma_L,
 *   R: an endpoint in Gamma_R,
 *   D: a degree-one M endpoint, hence an endpoint of the global path.
 *
 * Define
 *
 *   trace(g)=(multiset of unordered endpoint-type pairs of its components,
 *             intL, intR),
 *
 * where intL (respectively intR) is the number of degree-two gadget
 * vertices in Gamma_L (respectively Gamma_R).  This trace is the sector.
 * A D-D component has zero completion count here because S is nonempty and
 * it could not connect to F.
 *
 * Claim: N_g(n) depends only on trace(g), and the number of traces depends
 * only on k.
 *
 * Proof.  Suppose trace(g)=trace(g').  Match gadget components preserving
 * endpoint types, then match their L endpoints, R endpoints, internal
 * Gamma_L vertices and internal Gamma_R vertices.  Extend this to
 * sigma in Sym(Gamma_L) x Sym(Gamma_R).  Boundary vertices on the same side
 * are twins in S, so sigma is an automorphism of S.
 *
 * Replace every gadget chain with two Gamma endpoints by an auxiliary edge
 * joining those endpoints; replace a chain with a D endpoint by an endpoint
 * marker at its Gamma endpoint.  The assertion that F union g is one global
 * path is then determined by
 *
 *   (a) deg_F(gamma) <= 2-deg_g(gamma),
 *   (b) the auxiliary edges, endpoint markers and F form one spanning path,
 *   (c) the total number of degree-one global endpoints is two.
 *
 * These data use only the trace, not chain lengths or M labels.  Therefore
 * F -> sigma(F) is a bijection between the completions of g and g', proving
 * N_g=N_g'.  There are at most k components, six endpoint-type pairs and
 * intL,intR<=k-1, so only finitely many traces exist for fixed k.  QED.
 *
 * Exhaustive verification (evidence for the implementation, not part of the
 * general proof) gave
 *
 *       k    gadgets    traces    mismatches inside a trace
 *       3         12        12    0
 *       4        373        31    0
 *       5      16764        66    0       (n=4).
 *
 * For k=4 the counts 373/31 are stable for n=3,4,5.  Independence of n also
 * follows directly from the fixed relative neighborhoods of the M_s.
 *
 * COROLLARY A3 -- PROVED
 * ----------------------
 * If beta runs through traces, m_beta is the number of gadgets having trace
 * beta and N_beta is their common completion count, then
 *
 *                 A_k(n)=2*Sum_beta m_beta*N_beta(n).         (A3)
 *
 * The set of beta and every m_beta depend only on k.  This rigorously
 * replaces the formerly undefined phrase "expand the k middle rows/columns"
 * and supplies the missing finite sector space at the combinatorial level.
 * It does NOT yet construct a stationary transfer between different n.
 *
 * LEMMA B0 (TRUNCATED-RING MATRIX-TREE IDENTITY) -- PROVED
 * -------------------------------------------------------
 * Work in
 *
 *       R3=Z[x_v:v in V]/(x_v^3:v in V).
 *
 * Give edge {u,v} weight x_u*x_v, and let the weighted Laplacian be
 *
 *   Lap[u,v]=-x_u*x_v                     for u~v, u!=v,
 *   Lap[v,v]=x_v*Sum_{u~v} x_u.
 *
 * For any root v0, the ordinary Matrix-Tree Theorem, first in Z[x] and then
 * mapped to R3, gives
 *
 *   det Lap(v0|v0)=Sum_{unoriented Hamilton paths P}
 *                         Product_v x_v^deg_P(v)              in R3. (B0)
 *
 * Indeed a tree having a vertex of degree at least three vanishes in R3;
 * a spanning tree of maximum degree at most two is exactly a Hamilton path.
 * Let Phi:R3->Z be the Z-linear functional which sums the coefficients of
 * the unique normal form with exponents 0,1,2.  Then
 *
 *                 A_k(n)=2*Phi(det Lap(v0|v0)).               (B0')
 *
 * Phi is deliberately a linear functional, not substitution x_v=1:
 * substitution x_v=1 is not a ring homomorphism out of R3 because 1^3!=0.
 * This corrects another ambiguity in the former comment.
 *
 * LEMMA B1 (ALL-MINORS DICTIONARY) -- PROVED
 * ------------------------------------------------
 * Let W,W' be equally sized subsets of V.  Chaiken's all-minors Matrix-Tree
 * Theorem expresses
 *
 *   det Lap(W|W')=epsilon(W,W')*Sum_F sgn(pi_F)
 *                                      *Product_v x_v^deg_F(v),       (B1)
 *
 * where F has |W| components, each component contains exactly one element
 * of W and one of W', and pi_F is the induced bijection W->W'.  The theorem
 * is a polynomial identity over Z[x], hence remains true in R3.  There all
 * forests with a degree-three vertex vanish, leaving signed spanning linear
 * forests with prescribed root connectivity.
 *
 * Taking W,W' in Gamma supplies the algebraic objects needed for boundary
 * conditions in A2.  A fully executable transfer must still spell out the
 * finite signed combinations/coefficient functionals selecting each beta;
 * B1 proves that such boundary minors count forests, but does not by itself
 * compute the conjectural transfer coefficients.
 *
 * This resolves the old "cycle terms are absent" gap.  Individual terms of
 * a raw determinant expansion can cancel; no termwise claim is needed.
 * Each complete minor is, by (B1), already a signed sum of forests only.
 *
 * LEMMA B2 (DIVISION-FREE ELIMINATION) -- PROVED
 * ------------------------------------------------
 * Expand a row and column of every minor by repeated Laplace identities
 *
 *       det A=Sum_j (-1)^(i+j)*a[i,j]*det A(i|j).
 *
 * Laplace expansion holds over every commutative ring and uses no division.
 * Therefore it is valid in R3, which has zero divisors.  The formerly vague
 * word "eliminate" must mean these Laplace expansions, not a Schur complement
 * requiring an invertible pivot.  Together B1 and B2 give a rigorous,
 * mechanically checkable language for every intermediate boundary minor.
 *
 * PROPOSITION C0 (REFLECTION OBSTRUCTION) -- PROVED
 * ------------------------------------------------
 * Let T act on a finite-dimensional space U, let iota be an involution with
 * iota*T*iota=T, and suppose the input vector and output covector are iota
 * invariant.  If the generalized lambda-eigenspace inside the fixed space
 * U^iota has dimension at most one, then
 *
 *                     <out|T^n|in>
 *
 * contains no n*lambda^n term.
 *
 * Proof.  T preserves U^iota and only this restriction contributes to the
 * displayed scalar.  A generalized eigenspace of dimension at most one has
 * no Jordan block of size two.  The polynomial multiplying lambda^n thus has
 * degree zero.  QED.
 *
 * Consequence: the former folding explanation is impossible as written.
 * It first identified r with k-r and then claimed that the same folded pair
 * formed a 2-by-2 one-directional Jordan block.  Identification leaves only
 * one dimension, while a size-two Jordan block needs two.  Moreover
 *
 *                  [lambda 1; 0 lambda]
 *
 * does not commute with the operation exchanging its two basis vectors.
 * Thus reflection quotienting and that one-directional block cannot be the
 * same step.  For k=3 the implemented/observed expression
 *
 *                         A_3(n)=(n+6)*2^n
 *
 * illustrates the obstruction: its n*2^n term requires a size-two Jordan
 * chain on the reachable-and-observable scalar part.  For k=3 the formula is
 * now certified for all n; the obstruction concerns only the rejected
 * folding explanation, not the truth of that formula.
 *
 * Any reflection-equivariant proof of the conjectured odd-k squared central
 * factor must therefore exhibit at least two generalized central directions
 * in U^iota.  A plausible source is an imbalance token recording the side of
 * an unmatched central slot.  Its precise sector and one-directional coupling
 * have not yet been derived; they belong to the conjectural general spectral
 * law below.
 *
 * GENERAL SPECTRAL LAW -- CONJECTURAL; FIXED k<=7 CERTIFIED
 * ---------------------------------------------------------
 * The former attempted general proof assumed the following statements.
 *
 * (C1) Repeated outside-in Laplace expansion eventually gives an n-independent
 *      finite transfer T_k on suitable refinements of the trace sectors.
 *
 * (C2) Its relevant diagonal entries are
 *
 *                       lambda_r=r*(k-r).
 *
 * (C3) Noncentral reflected pairs contribute one simple factor.  For even k
 *      the central r=k/2 factor is simple.  For odd k an additional central
 *      generalized direction produces a size-two Jordan chain and hence a
 *      squared central factor.
 *
 * (C4) Exactly q=max(0,k-3) boundary layers are nonstationary.
 *
 * If C1--C4 hold, put d=ceil(k/2) and
 *
 *   C_k(X)=Product_{r=1..floor(k/2)}(X-r*(k-r))
 *              * (X-floor(k/2)*ceil(k/2))^[k odd]
 *         =X^d+c_1*X^(d-1)+...+c_d.                          (C5)
 *
 * They would imply uniformly in k that the program's recurrence
 *
 *   A_k(n)+c_1*A_k(n-1)+...+c_d*A_k(n-d)=0                  (C6)
 *
 * starts at n=d+max(0,k-3).  Independently of C1--C4, the insertion-state
 * theorem and finite-window certification in files/proved_results.md prove
 * this recurrence and its start point separately for every k=2,...,7.
 * For k=8 and unrestricted k it remains conjectural.  Examples are
 *
 *   k=3: A(n)=4*A(n-1)-4*A(n-2),                    n>=2;
 *   k=4: A(n)=7*A(n-1)-12*A(n-2),                  n>=3;
 *   k=5: A(n)=16*A(n-1)-84*A(n-2)+144*A(n-3),     n>=5.
 *
 * A uniform proof would still have to derive the general diagonal, the odd
 * central refinement, and q, or otherwise prove the same spectral law.  The
 * B1-minor transfer is one possible route, but it is no longer needed to
 * establish the already certified cases k=2,...,7.
 *
 * CERTIFICATES, NUMERICAL EVIDENCE, AND CHECKS
 * ---------------------------------------------
 * Initial values were produced by the definition DP in 179962_01.c, not by
 * fitting (C6).  --check recomputes affordable terms with that layered
 * Held--Karp kernel; it also invokes direct permutation enumeration for
 * 2*n+k<=10 and a separately written forward subset DP for 2*n+k<=16.
 *
 * For k=2,...,7, the finite-window computation is part of the proof because
 * the proved finite-state dimension bounds the residual recurrence order.
 * The affordable definition-level checks below additionally test that the C
 * implementation matches that proof.  For k=8 they remain finite evidence.
 *
 * Every embedded k<=8 list extends beyond the claimed recurrence boundary.
 * In particular, an independent k=8,n=9 computation used 872415206 DP states
 * and 4382.2 MiB and gave
 *
 *                   A_8(9)=1753844521231872,
 *
 * agreeing with (C6).  This is a genuine prediction check, not a proof.
 * Supplied A179966 values for k=8 begin
 *
 *   40320, 479306, 6564318, 99133496, 1572313392, 25415753280.
 *
 * Supplied A179967 values for k=9 are
 *
 *   362880, 5296790, 88422296, 1634227958, 32096768008, 649347224736.
 *
 * They stop at n=5.  The conjectural order-five recurrence would require
 * stationary seeds n=6..10, so k=9 is deliberately not exposed.
 *
 * IMPLEMENTATION COMPLEXITY AND SAFETY
 * ------------------------------------
 * For fixed k, generation through N uses O(ceil(k/2)*N) exact GMP
 * add-multiplications and O(ceil(k/2)) GMP integers apart from output.
 * Coefficients are constructed with checked int64 arithmetic.  Range output
 * uses _part.txt and is atomically renamed only after successful completion.
 * For k=2,...,7 the certificate proves that these generated values equal the
 * combinatorial definition.  For k=8, extrapolated values beyond the checked
 * prefix remain conditional on C8.
 *
 * Build (179957_01.c must be beside this file):
 *
 *   clang -O3 -std=c11 -Wall -Wextra -Wpedantic \
 *     -I/opt/homebrew/include -L/opt/homebrew/lib \
 *     179962_02.c -lgmp -o 179962_02
 *
 * Examples:
 *
 *   ./179962_02 --k 4 --upto 1000
 *   ./179962_02 --k 7 --term 10000
 *   ./179962_02 --k 8 --check 1000
 *
 * References:
 *   files/proved_results.md (finite-state proof and k<=7 certificates).
 *   S. Chaiken, all-minors Matrix-Tree Theorem (1982).
 *   R. Ehrenborg and S. van Willigenburg, Enumerative properties of
 *   Ferrers graphs, Discrete Comput. Geom. 32 (2004), 481--492.
 *   https://arxiv.org/abs/0706.2918
 *   OEIS A179962: https://oeis.org/A179962
 */

/* Import the exact definition-DP engine only for --check. */
#define main m2_imported_definition_dp_main
#include "179957_01.c"
#undef main

#include <gmp.h>

#define M2_MIN_K 2
#define M2_MAX_K 8
#define M2_DEFAULT_K 4
#define M2_DEFAULT_N 100
#define M2_DEFAULT_CHECK_N 1000
#define M2_MAX_N 1000000
#define M2_REFERENCE_MAX_TOTAL 22
#define M2_ARRAY_COUNT(a) (sizeof(a) / sizeof((a)[0]))

typedef enum {
    M2_RUN_UPTO,
    M2_RUN_TERM,
    M2_RUN_CHECK
} M2RunMode;

typedef struct {
    int k;
    int maximum_n;
    M2RunMode mode;
    uint64_t memory_mib;
} M2Options;

typedef struct {
    int degree;
    int first_recurrence_n;
    int64_t coefficient[8]; /* ascending powers, monic at [degree] */
} M2Recurrence;

typedef struct {
    uint64_t addmuls;
    double seconds;
} M2Stats;

static const char *const m2_k2_seed[] = {"2"};
static const char *const m2_k3_seed[] = {"6", "14"};
static const char *const m2_k4_seed[] = {"24", "90", "368"};
static const char *const m2_k5_seed[] = {
    "120", "646", "3984", "25384", "161136"
};
static const char *const m2_k6_seed[] = {
    "720", "5242", "44304", "399848", "3661824", "33461568"
};
static const char *const m2_k7_seed[] = {
    "5040", "47622", "521606", "6231544", "76972416",
    "957913824", "11902581120", "147689145984"
};
static const char *const m2_k8_seed[] = {
    "40320", "479306", "6564318", "99133496", "1572313392",
    "25415753280", "412583686272", "6690112284672",
    "108370981896192"
};

/* These lists extend beyond the seed boundary. */
static const char *const m2_k2_known[] = {
    "2", "2", "2", "2", "2", "2", "2", "2"
};
static const char *const m2_k3_known[] = {
    "6", "14", "32", "72", "160", "352", "768", "1664",
    "3584", "7680"
};
static const char *const m2_k4_known[] = {
    "24", "90", "368", "1496", "6056", "24440", "98408",
    "395576", "1588136", "6370040", "25532648", "102288056"
};
static const char *const m2_k5_known[] = {
    "120", "646", "3984", "25384", "161136", "1019616",
    "6433728", "40495488", "254319360", "1593945600"
};
static const char *const m2_k6_known[] = {
    "720", "5242", "44304", "399848", "3661824", "33461568",
    "305193408", "2779045440"
};
static const char *const m2_k7_known[] = {
    "5040", "47622", "521606", "6231544", "76972416",
    "957913824", "11902581120", "147689145984", "1830235823616"
};
static const char *const m2_k8_known[] = {
    "40320", "479306", "6564318", "99133496", "1572313392",
    "25415753280", "412583686272", "6690112284672",
    "108370981896192", "1753844521231872"
};

static _Noreturn void m2_die(const char *message)
{
    fprintf(stderr, "error: %s\n", message);
    exit(EXIT_FAILURE);
}

static bool m2_i64_add(int64_t a, int64_t b, int64_t *result)
{
    if ((b > 0 && a > INT64_MAX - b) ||
        (b < 0 && a < INT64_MIN - b)) {
        return false;
    }
    *result = a + b;
    return true;
}

static bool m2_i64_mul(int64_t a, int64_t b, int64_t *result)
{
    if (a == 0 || b == 0) {
        *result = 0;
        return true;
    }
    if (a > 0) {
        if ((b > 0 && a > INT64_MAX / b) ||
            (b < 0 && b < INT64_MIN / a)) {
            return false;
        }
    } else {
        if ((b > 0 && a < INT64_MIN / b) ||
            (b < 0 && a < INT64_MAX / b)) {
            return false;
        }
    }
    *result = a * b;
    return true;
}

static M2Recurrence m2_build_recurrence(int k)
{
    M2Recurrence recurrence;
    memset(&recurrence, 0, sizeof(recurrence));
    recurrence.coefficient[0] = 1;
    int degree = 0;
    int roots[8];
    int root_count = 0;
    for (int r = 1; r <= k / 2; ++r) {
        roots[root_count++] = r * (k - r);
    }
    if ((k & 1) != 0) {
        roots[root_count++] = (k / 2) * (k - k / 2);
    }
    for (int root_index = 0; root_index < root_count; ++root_index) {
        int64_t next[8] = {0};
        for (int power = 0; power <= degree; ++power) {
            int64_t product;
            int64_t sum = 0;
            if (!m2_i64_mul(recurrence.coefficient[power],
                            -(int64_t)roots[root_index], &product) ||
                !m2_i64_add(next[power], product, &sum)) {
                m2_die("recurrence coefficient overflow");
            }
            next[power] = sum;
            if (!m2_i64_add(next[power + 1],
                            recurrence.coefficient[power], &sum)) {
                m2_die("recurrence coefficient overflow");
            }
            next[power + 1] = sum;
        }
        ++degree;
        memcpy(recurrence.coefficient, next, sizeof(next));
    }
    recurrence.degree = degree;
    recurrence.first_recurrence_n = degree + (k > 3 ? k - 3 : 0);
    if (degree != (k + 1) / 2 ||
        recurrence.coefficient[degree] != 1 ||
        recurrence.first_recurrence_n <= 0) {
        m2_die("internal recurrence invariant failed");
    }
    return recurrence;
}

static const char *const *m2_seed_for_k(int k, size_t *count)
{
    switch (k) {
    case 2: *count = M2_ARRAY_COUNT(m2_k2_seed); return m2_k2_seed;
    case 3: *count = M2_ARRAY_COUNT(m2_k3_seed); return m2_k3_seed;
    case 4: *count = M2_ARRAY_COUNT(m2_k4_seed); return m2_k4_seed;
    case 5: *count = M2_ARRAY_COUNT(m2_k5_seed); return m2_k5_seed;
    case 6: *count = M2_ARRAY_COUNT(m2_k6_seed); return m2_k6_seed;
    case 7: *count = M2_ARRAY_COUNT(m2_k7_seed); return m2_k7_seed;
    case 8: *count = M2_ARRAY_COUNT(m2_k8_seed); return m2_k8_seed;
    default: m2_die("unsupported k while selecting seeds");
    }
    return NULL;
}

static const char *m2_known_term(int k, int n)
{
#define M2_KNOWN_CASE(value, array) \
    case value: return (size_t)n < M2_ARRAY_COUNT(array) ? array[n] : NULL
    switch (k) {
    M2_KNOWN_CASE(2, m2_k2_known);
    M2_KNOWN_CASE(3, m2_k3_known);
    M2_KNOWN_CASE(4, m2_k4_known);
    M2_KNOWN_CASE(5, m2_k5_known);
    M2_KNOWN_CASE(6, m2_k6_known);
    M2_KNOWN_CASE(7, m2_k7_known);
    M2_KNOWN_CASE(8, m2_k8_known);
    default: return NULL;
    }
#undef M2_KNOWN_CASE
}

static void m2_count128_to_mpz(mpz_t destination, Count128 source)
{
    uint64_t words[2] = {source.low, source.high};
    mpz_import(destination, 2U, -1, sizeof(words[0]), 0, 0, words);
}

static Count128 m2_definition_value(int n, int k, uint64_t memory_mib)
{
    if (n < 0 || k < 0 || n > (INT_MAX - k) / 2) {
        m2_die("2*n+k overflows int in definition check");
    }
    int total = 2 * n + k;
    int threshold = n + 1;
    DpStats stats;
    Count128 value = compute_dp(total, threshold, memory_mib, &stats);

    if (total > 1 && (value.low & UINT64_C(1)) != 0U) {
        m2_die("reversal parity failed in definition check");
    }
    if (total <= DIRECT_CHECK_MAX_N) {
        Count128 direct = direct_count(total, threshold);
        if (!count_equal(value, direct)) {
            m2_die("direct-permutation definition check failed");
        }
    }
    if (total <= INDEPENDENT_CHECK_MAX_N) {
        Count128 forward =
            count_from_u64(independent_forward_dp(total, threshold));
        if (!count_equal(value, forward)) {
            m2_die("independent forward-DP definition check failed");
        }
    }
    return value;
}

static void m2_verify_known(const mpz_t value, int n, int k)
{
    const char *known = m2_known_term(k, n);
    if (known == NULL) {
        return;
    }
    mpz_t expected;
    mpz_init(expected);
    if (mpz_set_str(expected, known, 10) != 0) {
        mpz_clear(expected);
        m2_die("invalid embedded known term");
    }
    if (mpz_cmp(value, expected) != 0) {
        fprintf(stderr, "error: known-value mismatch at n=%d,k=%d\n", n, k);
        mpz_clear(expected);
        exit(EXIT_FAILURE);
    }
    mpz_clear(expected);
}

static void m2_write_term(FILE *stream, int n, const mpz_t value)
{
    if (fprintf(stream, "%d ", n) < 0 ||
        mpz_out_str(stream, 10, value) == 0 ||
        fputc('\n', stream) == EOF) {
        m2_die("could not write a sequence term");
    }
}

/* Sequential generation with a degree-size rolling GMP ring. */
static void m2_generate(int k, int maximum_n, FILE *stream, mpz_t last,
                        bool verify_known, M2Stats *stats)
{
    M2Recurrence recurrence = m2_build_recurrence(k);
    size_t seed_count;
    const char *const *seed = m2_seed_for_k(k, &seed_count);
    if (seed_count != (size_t)recurrence.first_recurrence_n) {
        m2_die("seed length does not match recurrence boundary");
    }

    mpz_t *ring = calloc((size_t)recurrence.degree, sizeof(*ring));
    if (ring == NULL) {
        m2_die("could not allocate recurrence ring");
    }
    for (int i = 0; i < recurrence.degree; ++i) {
        mpz_init(ring[i]);
    }
    mpz_t next;
    mpz_t product;
    mpz_init(next);
    mpz_init(product);
    stats->addmuls = 0;
    clock_t begin = clock();

    for (int n = 0; n <= maximum_n; ++n) {
        mpz_ptr current;
        if ((size_t)n < seed_count) {
            current = ring[n % recurrence.degree];
            if (mpz_set_str(current, seed[n], 10) != 0) {
                m2_die("invalid embedded seed");
            }
        } else {
            mpz_set_ui(next, 0U);
            for (int lag = 1; lag <= recurrence.degree; ++lag) {
                int coefficient_index = recurrence.degree - lag;
                int64_t coefficient = recurrence.coefficient[coefficient_index];
                mpz_srcptr prior = ring[(n - lag) % recurrence.degree];
                if (coefficient < LONG_MIN || coefficient > LONG_MAX) {
                    m2_die("recurrence coefficient does not fit long");
                }
                mpz_mul_si(product, prior, (long)coefficient);
                mpz_sub(next, next, product);
                if (stats->addmuls == UINT64_MAX) {
                    m2_die("operation counter overflow");
                }
                ++stats->addmuls;
            }
            current = ring[n % recurrence.degree];
            mpz_swap(current, next);
        }
        if (verify_known) {
            m2_verify_known(current, n, k);
        }
        if (stream != NULL) {
            m2_write_term(stream, n, current);
        }
        if (n == maximum_n) {
            mpz_set(last, current);
        }
    }
    stats->seconds = (double)(clock() - begin) / (double)CLOCKS_PER_SEC;
    mpz_clear(product);
    mpz_clear(next);
    for (int i = 0; i < recurrence.degree; ++i) {
        mpz_clear(ring[i]);
    }
    free(ring);
}

static int m2_parse_nonnegative(const char *text, const char *label, int maximum)
{
    char *end = NULL;
    errno = 0;
    long value = strtol(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' ||
        value < 0 || value > maximum) {
        fprintf(stderr, "error: %s must be in 0..%d: %s\n",
                label, maximum, text);
        exit(EXIT_FAILURE);
    }
    return (int)value;
}

static int m2_parse_k(const char *text)
{
    int k = m2_parse_nonnegative(text, "K", M2_MAX_K);
    if (k < M2_MIN_K) {
        fprintf(stderr, "error: K must be in %d..%d: %s\n",
                M2_MIN_K, M2_MAX_K, text);
        exit(EXIT_FAILURE);
    }
    return k;
}

static void m2_usage(const char *program)
{
    fprintf(stderr,
            "usage: %s [MAX_N] [--k K]\n"
            "       %s --upto MAX_N [--k K]\n"
            "       %s --term N [--k K]\n"
            "       %s --check [MAX_N] [--k K] [--memory-mib M]\n"
            "\n"
            "Counts permutations of [2*n+k] whose adjacent absolute "
            "differences are > n.\n"
            "K is in %d..%d and N is in 0..%d; N is not limited by 2*n+k.\n"
            "Defaults: --k %d --upto %d; --check defaults to %d.\n",
            program, program, program, program, M2_MIN_K, M2_MAX_K,
            M2_MAX_N, M2_DEFAULT_K, M2_DEFAULT_N, M2_DEFAULT_CHECK_N);
}

static M2Options m2_parse_options(int argc, char **argv)
{
    M2Options options;
    options.k = M2_DEFAULT_K;
    options.maximum_n = M2_DEFAULT_N;
    options.mode = M2_RUN_UPTO;
    options.memory_mib = DEFAULT_MEMORY_MIB;
    bool have_k = false;
    bool have_n = false;
    bool have_mode = false;
    bool have_memory = false;

    for (int argument = 1; argument < argc; ++argument) {
        const char *text = argv[argument];
        if (strcmp(text, "--help") == 0 || strcmp(text, "-h") == 0) {
            m2_usage(argv[0]);
            exit(EXIT_SUCCESS);
        } else if (strcmp(text, "--k") == 0) {
            if (have_k || argument + 1 >= argc) {
                m2_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
            options.k = m2_parse_k(argv[++argument]);
            have_k = true;
        } else if (strcmp(text, "--memory-mib") == 0) {
            if (have_memory || argument + 1 >= argc) {
                m2_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
            options.memory_mib = parse_memory_mib(argv[++argument]);
            have_memory = true;
        } else if (strcmp(text, "--term") == 0 ||
                   strcmp(text, "--upto") == 0) {
            if (have_mode || have_n || argument + 1 >= argc) {
                m2_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
            options.mode = strcmp(text, "--term") == 0
                               ? M2_RUN_TERM : M2_RUN_UPTO;
            options.maximum_n = m2_parse_nonnegative(
                argv[++argument],
                options.mode == M2_RUN_TERM ? "N" : "MAX_N", M2_MAX_N);
            have_mode = true;
            have_n = true;
        } else if (strcmp(text, "--check") == 0) {
            if (have_mode) {
                m2_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
            options.mode = M2_RUN_CHECK;
            options.maximum_n = M2_DEFAULT_CHECK_N;
            have_mode = true;
            if (argument + 1 < argc && argv[argument + 1][0] != '-') {
                options.maximum_n = m2_parse_nonnegative(
                    argv[++argument], "CHECK_N", M2_MAX_N);
                have_n = true;
            }
        } else if (text[0] != '-') {
            if (have_n) {
                m2_usage(argv[0]);
                exit(EXIT_FAILURE);
            }
            options.maximum_n = m2_parse_nonnegative(
                text, "MAX_N", M2_MAX_N);
            have_n = true;
        } else {
            m2_usage(argv[0]);
            exit(EXIT_FAILURE);
        }
    }
    if (have_memory && options.mode != M2_RUN_CHECK) {
        m2_die("--memory-mib applies only to the independent --check DP");
    }
    return options;
}

static void m2_print_recurrence(int k)
{
    M2Recurrence recurrence = m2_build_recurrence(k);
    fprintf(stderr,
            "179962_02: k=%d, recurrence order=%d, first n=%d, C(X)=",
            k, recurrence.degree, recurrence.first_recurrence_n);
    for (int power = recurrence.degree; power >= 0; --power) {
        int64_t value = recurrence.coefficient[power];
        if (value == 0) {
            continue;
        }
        if (power != recurrence.degree) {
            fprintf(stderr, value < 0 ? " - " : " + ");
        } else if (value < 0) {
            fputc('-', stderr);
        }
        uint64_t magnitude = value < 0
                                 ? (uint64_t)(-(value + 1)) + 1U
                                 : (uint64_t)value;
        if (magnitude != 1U || power == 0) {
            fprintf(stderr, "%" PRIu64, magnitude);
            if (power > 0) {
                fputc('*', stderr);
            }
        }
        if (power > 0) {
            fputc('X', stderr);
            if (power > 1) {
                fprintf(stderr, "^%d", power);
            }
        }
    }
    fputc('\n', stderr);
}

static void m2_write_file(const char *argv0, int maximum_n, int k)
{
    char final_name[80];
    char part_name[80];
    int final_length = snprintf(final_name, sizeof(final_name),
                                "b179962_02_k%d.txt", k);
    int part_length = snprintf(part_name, sizeof(part_name),
                               "b179962_02_k%d_part.txt", k);
    if (final_length < 0 || (size_t)final_length >= sizeof(final_name) ||
        part_length < 0 || (size_t)part_length >= sizeof(part_name)) {
        m2_die("output filename is too long");
    }
    char *final_path = path_beside_executable(argv0, final_name);
    char *part_path = path_beside_executable(argv0, part_name);
    FILE *stream = fopen(part_path, "w");
    if (stream == NULL) {
        fprintf(stderr, "error: cannot open %s: %s\n",
                part_path, strerror(errno));
        free(final_path);
        free(part_path);
        exit(EXIT_FAILURE);
    }

    mpz_t last;
    mpz_init(last);
    M2Stats stats;
    m2_generate(k, maximum_n, stream, last, true, &stats);
    if (fflush(stream) != 0 || fclose(stream) != 0) {
        mpz_clear(last);
        free(final_path);
        free(part_path);
        m2_die("could not finish the output file");
    }
    if (rename(part_path, final_path) != 0) {
        fprintf(stderr, "error: cannot rename %s to %s: %s\n",
                part_path, final_path, strerror(errno));
        mpz_clear(last);
        free(final_path);
        free(part_path);
        exit(EXIT_FAILURE);
    }
    m2_print_recurrence(k);
    fprintf(stderr,
            "179962_02: n=0..%d, exact GMP recurrence, "
            "add-multiplies=%" PRIu64 ", %.3f s\n",
            maximum_n, stats.addmuls, stats.seconds);
    printf("wrote %s (n=0..%d, k=%d)\n", final_path, maximum_n, k);
    mpz_clear(last);
    free(final_path);
    free(part_path);
}

static void m2_check(int maximum_n, int k, uint64_t memory_mib)
{
    mpz_t recurrence_value;
    mpz_t reference_value;
    mpz_init(recurrence_value);
    mpz_init(reference_value);
    M2Stats stats;
    m2_generate(k, maximum_n, NULL, recurrence_value, true, &stats);

    int reference_maximum = (M2_REFERENCE_MAX_TOTAL - k) / 2;
    if (reference_maximum < 0) {
        reference_maximum = 0;
    }
    if (reference_maximum > maximum_n) {
        reference_maximum = maximum_n;
    }
    for (int n = 0; n <= reference_maximum; ++n) {
        M2Stats one_stats;
        m2_generate(k, n, NULL, recurrence_value, true, &one_stats);
        Count128 exact = m2_definition_value(n, k, memory_mib);
        m2_count128_to_mpz(reference_value, exact);
        if (mpz_cmp(recurrence_value, reference_value) != 0) {
            fprintf(stderr,
                    "error: recurrence/definition mismatch at n=%d,k=%d\n",
                    n, k);
            mpz_clear(reference_value);
            mpz_clear(recurrence_value);
            exit(EXIT_FAILURE);
        }
    }
    M2Recurrence recurrence = m2_build_recurrence(k);
    if (k <= 7) {
        printf("ok: certified order-%d recurrence from n=%d; embedded "
               "independent post-boundary values; exact definition DP "
               "through n=%d (2*n+k<=%d); direct permutations through "
               "total %d; independent forward DP through total %d; "
               "generated through n=%d (k=%d)\n",
               recurrence.degree, recurrence.first_recurrence_n,
               reference_maximum, M2_REFERENCE_MAX_TOTAL,
               DIRECT_CHECK_MAX_N, INDEPENDENT_CHECK_MAX_N, maximum_n, k);
    } else {
        printf("ok: finite checks passed for the conjectural order-%d "
               "recurrence from n=%d; exact definition DP through n=%d "
               "(2*n+k<=%d); direct permutations through total %d; "
               "independent forward DP through total %d; generated through "
               "n=%d (k=%d); this is not a full certificate\n",
               recurrence.degree, recurrence.first_recurrence_n,
               reference_maximum, M2_REFERENCE_MAX_TOTAL,
               DIRECT_CHECK_MAX_N, INDEPENDENT_CHECK_MAX_N, maximum_n, k);
    }
    mpz_clear(reference_value);
    mpz_clear(recurrence_value);
}

int main(int argc, char **argv)
{
    (void)&m2_imported_definition_dp_main;
    M2Options options = m2_parse_options(argc, argv);
    if (options.mode == M2_RUN_CHECK) {
        m2_check(options.maximum_n, options.k, options.memory_mib);
        return EXIT_SUCCESS;
    }
    if (options.mode == M2_RUN_TERM) {
        mpz_t value;
        mpz_init(value);
        M2Stats stats;
        m2_generate(options.k, options.maximum_n, NULL, value, true, &stats);
        m2_print_recurrence(options.k);
        fprintf(stderr,
                "179962_02: n=%d, k=%d, exact GMP recurrence, "
                "add-multiplies=%" PRIu64 ", %.3f s\n",
                options.maximum_n, options.k, stats.addmuls, stats.seconds);
        m2_write_term(stdout, options.maximum_n, value);
        mpz_clear(value);
        return EXIT_SUCCESS;
    }
    m2_write_file(argv[0], options.maximum_n, options.k);
    return EXIT_SUCCESS;
}
